# Define the path of the data and workspace
PATH:
  home: /home/maxiaoxiao/
  work_dir: Project3/lamost_dib/            # relative to home dir
  # mklink /d C:\Users\mxx\Desktop\All\data \\wsl.localhost\Ubuntu-22.04\home\mxx\DataSet\dib\cold_subfolder\
  data_dir: data/                           # relative to work dir
  catalog_path: input/LRS_X_Gaia-ebv.fits   # relative to work dir

  # DIB 5780
  output_dir: output/cold/dib5780/     # relative to work dir, i.e., home + work_dir + out_dir
  output_prefix: dib5780               # the prefix of the output files

  # DIB 6614
  # output_dir: output/cold/dib6614/      # relative to work dir, i.e., home + work_dir + out_dir
  # output_prefix: dib6614                # the prefix of the output files

# Filter conditions
FILTER:
  common:      # the common filter conditions for both
    teff_err_limit: 100
    logg_err_limit: 0.2
    feh_err_limit: 0.1
    rv_err_limit: 10
  reference:    # the reference sample
    snrr_lo: 50
    ebv_up: 0.03    # the upper limit of E(B-V)
    b_lo: 60        # the lower limit of galactic latitude, b, in degree
  target:       # the target sample
    snrr_lo: 100
